### ISSUE TITLE
申请修改博客信息-[002245]

### ISSUE THREAD

**Issue by Big-Cake-jpg** [zh-blogs/blog-daohang#14]
网站序号idx：002245
网站名称：大蛋糕的烘焙坊
需要修改的网站信息：链接、名称

---

诸君午安。
请将本站的链接更新为 https://lihaoyu.cn 、名称更新为“晓雨杂记”。
感激不尽。

**Comment by linlinzzo** [comment]
现在貌似后台好像修改不了？我分配一下。

**Comment by MYXXTS** [comment]
不好意思，因为后台近期在维护更新，我们在全力部署当中，完成之后会第一时间为您更新网站信息，请您谅解

**Comment by MYXXTS** [comment]
已对您的博客信息做出修正，您可以访问我们的网站进行查证，感谢您的反馈
