### ISSUE TITLE
服务漏洞报告-收录站点情况不确定

### ISSUE THREAD

**Issue by wznmickey** [zh-blogs/blog-daohang#16]
在
https://zhblogs.ohyee.cc/manager/join 尝试登记 wznmickey.com，提示已经在数据库中存在数据，但是在github的数据库中及网站内部搜索 https://zhblogs.ohyee.cc/?tab=blog_list&page=1&tags=&search=wznmickey 中均无法查到，无法确认该站点的收录情况。

**Comment by soxft** [comment]
您的博客似乎是因为 引用了 cdn.jsdelivt.net 导致访问速度过慢？ @OhYee 
链接已收录在 数据库内 但未展示, 稍等讨论下
