### ISSUE TITLE
服务漏洞报告-收录站点情况不确定x2

### ISSUE THREAD

**Issue by SinzMise** [zh-blogs/blog-daohang#17]
在
https://zhblogs.ohyee.cc/manager/join 尝试登记 blog.sinzmise.top，提示已经在数据库中存在数据，但是在github的数据库中及网站内部搜索 https://zhblogs.ohyee.cc/?tab=blog_list&page=1&tags=&search=https%3A%2F%2Fblog.sinzmise.top%2F 或 https://zhblogs.ohyee.cc/?tab=blog_list&page=1&tags=&search=blog.sinzmise.top 中均无法查到，无法确认该站点的收录情况。
这个也有人反映过：
![image](https://github.com/zh-blogs/blog-daohang/assets/120767492/92ea7bd9-e0c9-4899-b1d7-c9ca712426a3)
但目前可以确定的是我站点没引入cdn.jsdelivr.net

**Comment by soxft** [comment]
已审核通过，的确是在审核中，后续会优化相应提示，提高审核效率。
