### ISSUE TITLE
申请修改博客信息-[002110]

### ISSUE THREAD

**Issue by thun888** [zh-blogs/blog-daohang#18]
网站序号idx：002110
网站名称：Thun888's Blog
需要修改的网站信息：将链接更新为`https://blog.hzchu.top`

**Comment by gtxykn0504** [comment]
已经修改啦

**Comment by thun888** [comment]
好的，谢谢


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月5日(周五) 下午5:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zh-blogs/blog-daohang] 申请修改博客信息-[002110] (Issue #18)




 
Closed #18 as completed.
 
&mdash;
