### ISSUE TITLE
服务漏洞报告-收录站点情况不确定x3

### ISSUE THREAD

**Issue by aquausora** [zh-blogs/blog-daohang#19]
请在下方描述漏洞的出现地址（url）、漏洞截图、可能的复现方式、漏洞出现时间。如需进行服务不可用性报告，请使用开发人员工具截图“网络”tab。谢谢配合。

在 https://zhblogs.ohyee.cc/manager/join 尝试登记 champhoon.xyz，提示该博客已存在, 请勿重复添加，但其在网站内部搜索无法查到，无法确认该站点的收录情况。

与以下两个issue出现的问题一致：
https://github.com/zh-blogs/blog-daohang/issues/16
https://github.com/zh-blogs/blog-daohang/issues/17

**Comment by linlinzzo** [comment]
可能是已经提交到数据库但还未被审核。

**Comment by linlinzzo** [comment]
登录后台看了一下，情况的确是这样，已经为你审核。
