### ISSUE TITLE
服务漏洞报告-收录站点情况不确定x4

### ISSUE THREAD

**Issue by sifangbazhu** [zh-blogs/blog-daohang#21]
请在下方描述漏洞的出现地址（url）、漏洞截图、可能的复现方式、漏洞出现时间。如需进行服务不可用性报告，请使用开发人员工具截图“网络”tab。谢谢配合。
提交博客www.sifangbazhu.tech提示已存在，但搜索不到
与
#19
#17
#16
一样

**Comment by soxft** [comment]
先前为您标注了 文章过少，现已经手动通过了。
