### ISSUE TITLE
[Document Issue]-README 坏链

### ISSUE THREAD

**Issue by Lafcadia** [zh-blogs/blog-daohang#22]
请在下方描述漏洞的出现地址（url）、漏洞截图、可能的复现方式、漏洞出现时间。如需进行服务不可用性报告，请使用开发人员工具截图“网络”tab。谢谢配合。

本仓库README.md中的此[链接](https://github.com/zh-blogs/blog-daohang#:~:text=%E6%A0%87%E5%87%86%E8%AF%B4%E6%98%8E-,%E5%8D%9A%E5%AE%A2%E5%AE%9A%E4%B9%89,-%E6%9C%AC%E9%A1%B9%E7%9B%AE%E5%AF%B9%E4%BA%8E)已无法打开。

**Comment by Lafcadia** [comment]
（同一页面下的“精选博客”也一样）

**Comment by MYXXTS** [comment]
请直接进入仓库document文件夹查看临时版本，后续会做更新

**Comment by Lafcadia** [comment]
> 请直接进入仓库document文件夹查看临时版本，后续会做更新

感谢
