### ISSUE TITLE
项目维护意向调查

### ISSUE THREAD

**Issue by MYXXTS** [zh-blogs/blog-daohang#24]
各位 中文博客列表导航 项目组成员们，

大家好！

为了更好地维护和发展该项目，我们决定对组织内的所有成员进行一次维护意向调查。我们的组织主要有两个方向需要大家的支持和贡献：

- 程序开发：包括编写代码、修复bug、添加新功能等。
- 数据列表维护：包括数据的收集、整理、更新和验证等。

由于之前的种种原因，该项目的维护暂时停滞了一段时间。现在，我们希望正式将该项目从 V2 版本推进到 V3 版本，包括但不限于前端、后端、数据列表、项目标准、项目合作等方面。

为了确保每个方向都能得到及时的维护和改进，请各位在本Issue下回复以下问题：

您更愿意参与哪个方向的维护工作？（前端开发 / 后端开发 / 数据列表维护 / 项目标准维护 / 项目合作维护 / 不参与维护（可多选））
您是否有其他建议或意见，帮助我们更好地开展维护工作？
请大家以北京时间为准，在一周内回复，我们将根据大家的反馈进行合理的分配和安排。

感谢您的支持和参与！

祝好

林林 沐云湘夕
中文博客列表导航

**Comment by linlinzzo** [comment]
@huziyan1 @jonepengcn @Timozaici @wibus-wee @jsun969

**Comment by gtxykn0504** [comment]
数据列表维护 / 项目标准维护

**Comment by MYXXTS** [comment]
数据列表维护 / 项目标准维护

**Comment by linlinzzo** [comment]
@Redish101 @Mabbs @Changrui0101 @Lfhsheng @hydrogenoxide-user

**Comment by Timozaici** [comment]
不参与维护(由于工作繁忙,目前无精力参与维护工作) : )

**Comment by jsun969** [comment]
抱歉，学业繁忙，暂不参与维护

**Comment by wibus-wee** [comment]
有意向..但是需要重新学一些东西不然什么都写不了😐

**Comment by linlinzzo** [comment]
@Innei @OhYee @soxft @zkeq @Amitabha

**Comment by MYXXTS** [comment]
@Lafcadia @gtxykn0504 @waterelegance @liangmiQwQ @linhaii @yzqzss @hilllei

**Comment by MYXXTS** [comment]
> 有意向..但是需要重新学一些东西不然什么都写不了😐

有意向即可，我们在做统计，麻烦选择一下意向方向

**Comment by aquausora** [comment]
数据列表维护 / 项目标准维护

**Comment by soxft** [comment]
意向做项目后端吧，但是还是有些忙的

**Comment by MYXXTS** [comment]
> 意向做项目后端吧，但是还是有些忙的

好的，感谢

**Comment by MYXXTS** [comment]
> 不参与维护(由于工作繁忙,目前无精力参与维护工作) : )

好的，祝学业顺利

**Comment by MYXXTS** [comment]
> 抱歉，学业繁忙，暂不参与维护

好的，祝学业顺利

**Comment by wibus-wee** [comment]
意向做前端吧

但是真得重学一些东西...且最近在外进行一个放假

**Comment by MYXXTS** [comment]
> 意向做前端吧
> 
> 但是真得重学一些东西...且最近在外进行一个放假

好，假期愉快，等你回来

**Comment by Lafcadia** [comment]
有意向，但还需要学些东西。

**Comment by Lafcadia** [comment]
意向做列表维护吧。

**Comment by Mabbs** [comment]
本来想看看后端，结果是Go的🤣整不来，不过如果是需要python做数据处理可以整

**Comment by MYXXTS** [comment]
> 本来想看看后端，结果是Go的🤣整不来，不过如果是需要python做数据处理可以整

好的，谢谢

**Comment by Lfhsheng** [comment]
> @Redish101 @Mabbs @Changrui0101 @Lfhsheng @hydrogenoxide-user

学业繁忙，无暇维护

**Comment by jonepengcn** [comment]
学业繁忙，暂无维护意向。怀念曾经的岁月，感激当初的邀请。此去经年，应是良辰好景虚设。
祝愿项目组再觅忠志之士，蒸蒸日上。

**Comment by MYXXTS** [comment]
> > @Redish101 @Mabbs @Changrui0101 @Lfhsheng @hydrogenoxide-user
> 
> 学业繁忙，无暇维护

感谢回复，祝学业顺利

**Comment by MYXXTS** [comment]
> 学业繁忙，暂无维护意向。怀念曾经的岁月，感激当初的邀请。此去经年，应是良辰好景虚设。 祝愿项目组再觅忠志之士，蒸蒸日上。

感谢回复，祝学业顺利

**Comment by MYXXTS** [comment]
@huziyan1  @Redish101 @Changrui0101 @hydrogenoxide-user @Innei @OhYee @zkeq @Amitabha @waterelegance @liangmiQwQ @linhaii @yzqzss @hilllei 很抱歉打扰，但是请尽快回复，谢谢各位

**Comment by zkeq** [comment]
工作事务繁忙, 暂无维护意愿

**Comment by OhYee** [comment]
日常维护没问题，后端可以推到v3

前端看能不能找来人吧（或者保持现在的前端）

**Comment by redish101** [comment]
意向做后端，但是可能只假期有时间维护

**Comment by Innei** [comment]
工作事务繁忙, 暂无维护意愿

**Comment by liangmiQwQ** [comment]
前端开发 曾经参与过搜索引擎编写后期放弃，随后进行了前端的细致学习，暑期假期精力较为充沛，有时间进行一些开发

**Comment by MYXXTS** [comment]
> 意向做后端，但是可能只假期有时间维护

> 前端开发 曾经参与过搜索引擎编写后期放弃，随后进行了前端的细致学习，暑期假期精力较为充沛，有时间进行一些开发

请查收邮件，已经邀请至对应的开发组

**Comment by MYXXTS** [comment]
感谢各位的能够回复本Issue，此Issue就此关闭，祝愿各位工作顺利，学业有成，事事顺利
