### ISSUE TITLE
现有标签合并·存废讨论

### ISSUE THREAD

**Issue by aquausora** [zh-blogs/blog-daohang#27]
截至今日，所有积压未审的博客皆已审核完毕，接下来准备开始规整标签。
依据项目现有标签，拟对其做出以下调整：

### 删除

- [x] 删除 博客

> _我们本身就是中文博客列表导航，在这里的都是博客。_

- [x] 删除 深度好文
> _与推荐功能重复。_

- [x] 删除 学生博客、小学生、新站、管理添加
> _这些标签并无必要。_

- [x] 删除 访问慢、水文
> _或难以判定。_

- [x] 删除 网站
> _含义模糊，且已有建站、Web、网络、互联网、http、html、前端等等足够多的可以涵盖网站可能表示的含义的标签。_

### 合并

- [x] 合并 数据库、sql 为 数据库
- [x] 合并 科研、科学研究 为 科研
- [x] 合并 投资、理财 为 投资理财
- [x] 合并 记录、简记、日记、记事 为 记录
- [x] 合并 生活、日常、人生、生活记录、生活小记 为 生活
- [x] 合并 技术、技术博客、轻技术、技术分享 为 技术
- [x] 合并 杂录、短录 为 杂录
- [x] 合并 资料收集、收集 为 收集
- [x] 合并 随笔、生活随笔、随想 为 随笔
- [x] 合并 Web开发、Web 为 Web
- [x] 合并 阅读、读书 为 阅读
- [x] 合并 旅行、旅游 为 旅行
- [x] 合并 网络、计算机网络 为 网络
- [x] 合并 自动化开发、独立开发、独立开发者、开发笔记 为 开发
- [x] 合并 Windows、windows 为 Windows
- [x] 合并 编程、编程技术 为 编程
- [x] 合并 折腾、爱折腾 为 折腾
> _语义相似，内容基本一致。_

- [x] 合并 新闻、资讯 为 新闻资讯（或资讯）
- [x] 合并 动漫、追番、二次元、洛天依、锦依卫 为 动漫
- [x] 合并 影评、观影、电影、影视 为 影视
- [x] 合并 评论、简评 为 评论
- [x] 合并 杂谈、心路历程、想法 为 杂录
- [x] 合并 经验分享、经验 为 经验
- [x] 合并 统计、分析 为 统计分析
- [x] 合并 产品设计、产品观、产品 为 产品设计
- [x] 合并 敏感、部分内容不宜展示 为 敏感内容
> _语义相近，内容基本一致。_

- [x] 合并 微信小程序、小程序 为 小程序
- [x] 合并 机器学习、深度学习 为 深度学习
- [x] 合并 Office、Excel 为 Office
- [x] 合并 工具、效率工具 为 工具
- [x] 合并 测评、开箱、主机测评、数码测评 为 测评
- [x] 合并 分享、推荐、软件推荐、应用推荐、网站推荐 为 分享
- [x] 合并 服务器、vps 为 服务器
- [x] 合并 文学、美文 为 文学
- [x] 合并 攻防、网络攻防 为 网络攻防
- [x] 合并 英文、英文网站 为 英文
- [x] 合并 前端、前端笔记 为 前端
- [x] 合并 教育、教师 为 教育
- [x] 合并 加密货币、比特币 为 加密货币
- [x] 合并 图像处理、图片 为 图片
- [x] 合并 安全、网络安全、信息安全、应用安全、网安 为 安全
- [x] 合并 Mac、MacOS 为 Mac
- [x] 合并 笔记、Note、课程笔记、笔记本 为 笔记
- [x] 合并 竞赛、信息学竞赛 为 竞赛
- [x] 合并 计算机、计算机基础 为 计算机
> _相关标签仅一个分支，且相应博客都比较少，无必要继续细分。_

### 修改

- [x] 修改 electron 为 Electron
- [x] 修改 uos 为 UOS
- [x] 修改 springboot 为 Spring Boot 
- [x] 修改 http 为 HTTP
- [x] 修改 html 为 HTML
- [x] 修改 emacs 为 Emacs
- [x] 修改 next.js 为 Next.js 
- [x] 修改 devops 为 DevOps
- [x] 修改 react-native 为 React Native
> _规范拼写。_

- [x] 修改 vscode插件 为 VS Code
> _该标签仅一个博客，分得太细。_

**Comment by linlinzzo** [comment]
建议将列表改成待办的形式，等会处理完一个标签勾一项。

**Comment by aquausora** [comment]
> 建议将列表改成待办的形式，等会处理完一个标签勾一项。

改好啦

**Comment by linlinzzo** [comment]
@MYXXTS 你看一下这些有没有疑义，我看都可以。

**Comment by MYXXTS** [comment]
已做审阅，同意通过均已勾选
未勾选的内容可以继续讨论
可以写一个文档对tag进行解释，提交PR合并至MYXX分支

**Comment by linlinzzo** [comment]
@MYXXTS 那我看没什么疑议的就可以到后台去操作了吧？

**Comment by MYXXTS** [comment]
可以

**Comment by aquausora** [comment]
有几处是我编辑还有字符替换时出现的错误，已修改

- 合并 网络、计算机网络 为 网络
- 合并 React、react-native 为 React
- 修改 springboot 为 Spring-Boot
- 修改 vscode插件 为 VS-Code

**Comment by MYXXTS** [comment]
已查阅

> 有几处是我编辑还有字符替换时出现的错误，已修改
> 
> * 合并 网络、计算机网络 为 网络
> * 合并 React、react-native 为 React
> * 修改 springboot 为 Spring-Boot
> * 修改 vscode插件 为 VS-Code

该评论后两个可以通过，请去除短横线

**Comment by aquausora** [comment]
短横线已去除（一开始以为标签不能有空格）

针对部分未通过的拟修改：

- **取消合并 杂录、短录、资料收集、收集 为 杂录**
  - 合并 杂录、短录 为 杂录
  - 合并 收集、资料收集 为 收集

- **取消合并 影评、观影、电影、影视 为 影评**
  - 合并 影评、观影 为 影评
  - 合并 电影、影视 为 影视

- **取消合并 杂谈、经验分享、经验、心路历程、想法 为 杂谈**
  - 合并 经验分享、经验 为 经验
  - 合并 心路历程、想法 为 想法

- **取消合并 React、react-native 为 React （好像确实是两个东西，草率了）**
  - 修改 react-native 为 React Native

---

合并「敏感」和「部分内容不宜展示」这块，我的主要想法是这样的，从#28 中拟定的定义来看，「部分内容不宜展示」拟为「依照法律法规要求，含有应当限制展示内容的博客」，这个定义实际涵盖了「敏感」的概念。

虽然实际运用上，可能是为了进一步区分政治内容和NSFW内容，但是由于这两个实质上的警示Tag打上之后，是不会被展示的，专门区分开来的意义就没有那么大——首先是博主自己看不见，其次，它也只是为了让审核员只需知道其不能通过的原因：有不宜展示的内容。

如若先暂时维持现状的话，那么其实 敏感 这个标签也要补充进警示Tag。

---

其余未通过的，若无其他意见就暂时不做修改

**Comment by MYXXTS** [comment]
修正：之后提交文档至process分支，刚才我将myxx分支删除了，该分支由于是很久之前新建的分支，导致该分支名称不符合规范，后续我会上传新的分支作为新标准的制定仓库，请拟定修改相关标准，后续合并

**Comment by aquausora** [comment]
> 修正：之后提交文档至process分支，刚才我将myxx分支删除了，该分支由于是很久之前新建的分支，导致该分支名称不符合规范，后续我会上传新的分支作为新标准的制定仓库，请拟定修改相关标准，后续合并

好的，等我把tag兼并一波，然后把一些出现频率高的tag整理下，写一个这些高频tag解释的草稿

**Comment by MYXXTS** [comment]
可以进行推送了，请签名推送

**Comment by MYXXTS** [comment]
依照本Issue最初提出的修改内容，剩余未通过批注如下：
- [x] 删除 雨露均沾 // 该 Tag 是独立于主 Tag 综合的另一个标签，表示基于博客内容大方向的前提之下的内容繁杂，没有主要内容方向
- [x] 合并 杂录、短录、资料收集、收集 为 杂录 // 可以合并杂录、短录为杂录；资料收集和收集为收集
- [x] 合并 影评、观影、电影、影视 为 影评 // 合并为影视
- [x] 合并 杂谈、经验分享、经验、心路历程、想法 为 杂谈 // 合并杂谈、心路历程、想法为杂录；合并经验分享、经验为经验
- [x] 合并 敏感、部分内容不宜展示 // 合并为敏感内容
- [x] 合并 React、react-native 为 React // 两个并非同一个方向的技术栈，不予合并，但是请规范标签格式
- [x] 合并 机器学习、深度学习 为 机器学习 // 合并为深度学习
- [x] 合并 攻防、网络攻防 为 攻防 // 合并为网络攻防
- [x] 合并 教育、教师 为 教育 // 合并允许，看漏了……
- [x] 合并 图像处理、图片 为 图像处理 // 合并为图片

**Comment by aquausora** [comment]
现存所有标签合并·删除工作已完成
