### ISSUE TITLE
补充部分警示Tag

### ISSUE THREAD

**Issue by aquausora** [zh-blogs/blog-daohang#28]
[blog-daohang](https://github.com/zh-blogs/blog-daohang/tree/main)/document/Tag.md 中提到了三种警示Tag，分别为 无法访问、文章较少和非原创。

目前，在维护过程中，还出现了 无内容、部分内容不宜展示 的Tag，一般被打上这些Tag的博客也不会被展示。

因此，是否考虑将 无内容 和 部分内容不宜展示 也列入警示Tag，并规范其所代表的含义。

| Tag名称 | 所代表含义 |
| --- | --- |
| 无内容 | 待讨论补全 |
| 部分内容不宜展示 | 待讨论补全 |

另，我审核时，所有存在https问题的博客也都没有展示，但是由于缺乏相关Tag，所以暂时都没有做标记，是否应该也应该添加一个类似于 SSL错误 的警示Tag。

**Comment by linlinzzo** [comment]
无内容：博客没有有效文章或文章较少，且有保持观察的必要。
部分内容不宜展示：依照法律法规要求，含有应当限制展示的内容的博客。

个人观点

**Comment by MYXXTS** [comment]
| Tag名称 | 所代表含义 |
| --- | --- |
| 无内容 | 无具体内容，不代表文章较少，与文章较少进行区分 |
| 部分内容不宜展示 | 依照法律法规要求，含有应当限制展示内容的博客 |

该内容请补全文档提交PR合并至MYXX

**Comment by aquausora** [comment]
> Tag名称	所代表含义
> 无内容	无具体内容，不代表文章较少，与文章较少进行区分
> 部分内容不宜展示	依照法律法规要求，含有应当限制展示内容的博客
> 该内容请补全文档提交PR合并至MYXX

好的，那么是否考虑加一个ssl错误的标签

**Comment by MYXXTS** [comment]
可以考虑，但是不建议，如果说需要添加这个标签的话，我们需要完善博客检测的相关代码

**Comment by MYXXTS** [comment]
修正：之后提交文档至process分支，刚才我将myxx分支删除了，该分支由于是很久之前新建的分支，导致该分支名称不符合规范，后续我会上传新的分支作为新标准的制定仓库，请拟定修改相关标准，后续合并

**Comment by aquausora** [comment]
> 可以考虑，但是不建议，如果说需要添加这个标签的话，我们需要完善博客检测的相关代码

好的，可以的话最好能够完善下，那就先暂时维持出现ssl错误的博客不打相应标签，但不予展示

**Comment by MYXXTS** [comment]
可以进行推送了，请签名推送
