### ISSUE TITLE
常用副标签的含义规制草案

### ISSUE THREAD

**Issue by aquausora** [zh-blogs/blog-daohang#39]
初步规制了当前数量超过 10 个的副标签的含义，拟讨论修订后写入 Tag.md。
 做些增删后可作 #38 分类优化的参考

注：不包括诸如 Java、HTML、Hexo 这类直接拿相关编程语言或是技术栈名称命名的标签。

| Tag 名称 |               代表含义               |
| :------: | :--------------------------------------: |
|   记录   | 个人生活中方方面面的内容记录 |
|   随笔   | 对个人感想、生活片段等内容的随性记录 |
|   杂谈   | 涵盖各种话题、观点与个人想法 |
|   思考   | 对某个话题进行深度思考和分析 |
|   经验   | 讲述个人经验、技巧和见解 |
|   笔记   | 对于接纳信息的记录、整理与消化 |
|   开发   | 分享相关开发经验与成果 |
|   编程   | 有关编程语言、代码示例和编程技巧 |
|   网络   | 关于网络技术的一切内容 |
|   前端   | 关于前端技术的内容 |
|   后端   | 关于后端技术的内容 |
|   服务器   | 有关服务器的配置、管理和维护 |
|   数据库   | 有关数据库的配置、管理和维护 |
|   建站   | 有关网站的搭建、设计和维护 |
|   互联网   | 关于互联网发展与应用的内容 |
|   算法   | 关于算法设计、分析和应用的内容 |
|   安全   | 关于网络安全、隐私与数据保护的内容 |
|   深度学习   | 关于深度学习技术、模型和应用的内容 |
|   教程   | 专注于详细的学习步骤与操作指导 |
|   测评   | 对产品、服务或软件的详细评测 |
|   分享   | 关于分享与推荐的一切内容 |
|   软件工具   | 软件工具的推荐、教程与评测 |
|   资源   | 提供各类资源的获取渠道 |
|   知识   | 分享各类知识与相关学习资料 |
|   学习   | 总结学习方法与学习心得 |
|   科研   | 分享科学研究的方法或成果 |
|   新闻资讯   | 聚合最新的新闻和资讯消息 |
|   科技   | 聚焦科技发展、趋势与创新 |
|   动漫   | 有关二次元、ACGN 的一切内容 |
|   游戏   | 关于游戏的评测、攻略和游戏设备 |
|   摄影   | 展示摄影技巧、摄影作品和摄影设备 |
|   音乐   | 分享音乐评论、音乐推荐和音乐设备 |
|   影视   | 有关电影、电视剧的评论、推荐和影视设备 |
|   文学   | 有关文学作品的摘抄、分享和创作 |
|   阅读   | 分享读书笔记和阅读感想 |
|   旅行   | 分享旅行经历和旅行攻略 |
|   雨露均沾   | 涵盖广泛话题，无突出的内容方向 |

**Comment by MYXXTS** [comment]
可直接写入
