### ISSUE TITLE
[Modify & Improve]-<ROYWANG>-<000520>

### ISSUE THREAD

**Issue by roywangdev** [zh-blogs/blog-daohang#44]
### 博客名称

ROYWANG

### 博客 idx

000520

### 博客 URL

https://rise.rs/

### 修改或完善的字段

博客 URL

### 修改或完善的内容

博客描述：知善恶，懂因果，明是非，擢己身。
博客URL：https://roy.wang
博客RSS订阅地址：https://roy.wang/feed/

**Comment by linlinzzo** [comment]
已对信息进行修改。

新的网站原本已在数据库中存在，已删除。
