### ISSUE TITLE
[Proposal]-前端渲染-添加暗黑模式

### ISSUE THREAD

**Issue by liangmiQwQ** [zh-blogs/blog-daohang#54]
### 建议方向

其他

### 其他建议方向

前端渲染

### 建议内容

目前v2的项目中暂未适配暗黑模式，打算在v3中添加暗黑模式，需要重新设计暗黑模式logo等，增强网站适配性

**Comment by MYXXTS** [comment]
好的，正在着手重构LOGO

**Comment by MYXXTS** [comment]
[zhblogs.zip](https://github.com/user-attachments/files/16327429/zhblogs.zip)
