### ISSUE TITLE
[Modify & Improve]-<可可托海没有海>-< 002357 >

### ISSUE THREAD

**Issue by darmau** [zh-blogs/blog-daohang#55]
### 博客名称

可可托海没有海

### 博客 idx

002357

### 博客 URL

https://darmau.co/zh

### 修改或完善的字段

博客 RSS 订阅地址

### 修改或完善的内容

https://darmau.co/zh/article/rss.xml
https://darmau.co/zh/album/rss.xml
https://darmau.co/zh/thought/rss.xml

**Comment by MYXXTS** [comment]
很抱歉，由于我们目前程序不完善，对于多RSS无法支持，请选择一个您的主要的RSS连接

**Comment by darmau** [comment]
第一个，文章的

**Comment by MYXXTS** [comment]
好的，感谢回复，已处理，后续程序支持多RSS的情况下，我们会第一时间添加
