### ISSUE TITLE
[Modify & Improve]-<Leo2011 的博客>-<003674>

### ISSUE THREAD

**Issue by worker2011** [zh-blogs/blog-daohang#57]
### 博客名称

Leo2011的博客

### 博客 idx

003674

### 博客 URL

https://leo2011.pages.dev/

### 修改或完善的字段

博客名称, 博客 URL, 博客描述, 博客 RSS 订阅地址, 博客网站地图（SiteMap）地址, 博客所用程序（架构）, 博客标签（Tag）

### 修改或完善的内容

博客名称；Leo2011 的博客
博客 URL：https://leo2011.eu.org/
博客描述：一个蒟蒻的 OI 日记
博客 RSS 订阅地址：https://leo2011.eu.org/atom.xml
博客网站地图（SiteMap）地址：https://leo2011.eu.org/sitemap.xml
博客所用程序（架构）：Hexo
博客标签（Tag）：科技，编程，技术，算法，竞赛，C/C++，Python

**Comment by MYXXTS** [comment]
相关信息已经更新，感谢您的反馈

**Comment by worker2011** [comment]
这么晚了没想到这么快，感谢管理员大大~
