### ISSUE TITLE
[Abnormal]-<懋和道人>-<002195>

### ISSUE THREAD

**Issue by wulintang** [zh-blogs/blog-daohang#58]
### 博客名称

懋和道人

### 博客 idx

002195

### 博客 URL

https://www.lizhichen.cn

### 博客异常类型

博客无法访问

### 其他异常类型

URL已经更换成了https://www.dao.js.cn，望同步。

**Comment by MYXXTS** [comment]
相关信息已经更新，您的其余链接信息也一并更新，由于您的网站订阅替换之后无法访问，因此订阅链接已被移除，感谢您的反馈

**Comment by wulintang** [comment]
> 相关信息已经更新，您的其余链接信息也一并更新，由于您的网站订阅替换之后无法访问，因此订阅链接已被移除，感谢您的反馈

也就是说，我所有的域名都更换成了www.dao.js.cn，包括订阅的https://www.dao.js.cn/feed.php
谢谢你们了，福生无量。

**Comment by MYXXTS** [comment]
根据您的补充信息已经更新
