### ISSUE TITLE
喵二の小博客-更新博客 url

### ISSUE THREAD

**Issue by miaoermua** [zh-blogs/blog-daohang#60]
### 博客名称

喵二の小博客

### 博客 idx

000191

### 博客 URL

https://www.miaoer.xyz

### 修改或完善的字段

博客 URL

### 修改或完善的内容

博客 url：https://www.miaoer.net

**Comment by MYXXTS** [comment]
相关信息已做更改，感谢反馈，查询到贵站分类信息缺失，可以的话还请完善分类信息

**Comment by miaoermua** [comment]
> 相关信息已做更改，感谢反馈，查询到贵站分类信息缺失，可以的话还请完善分类信息

并没有很明显的内容区分，按照“综合”或者“技术”分类也行

**Comment by MYXXTS** [comment]
已添加至技术，感谢反馈
