### ISSUE TITLE
[Modify & Improve]-<静风说>-<002837>

### ISSUE THREAD

**Issue by jfsay** [zh-blogs/blog-daohang#61]
### 博客名称

静风说

### 博客 idx

002837

### 博客 URL

https://www.jfsay.com

### 修改或完善的字段

博客 URL, 博客 RSS 订阅地址

### 修改或完善的内容

博客URL: https://www.jfsay.com
博客RSS: https://www.jfsay.com/feed

**Comment by MYXXTS** [comment]
已修改，感谢反馈
